### ISSUE TITLE
Support null/empty values

### ISSUE THREAD

**Issue by slhck** [levibostian/dotenv#9]
This is a feature request.

When I add empty env variables like:

```
ELASTICSEARCH_TEST_URL=
```

Or:

```
ELASTICSEARCH_TEST_URL=""
```

These are not resolved, and therefore not available in the program code.

Feature: Make empty variables available in `Env`, but simply set to an empty string (in case of `""`), or `null` (in case of no value) so that you can programmatically deal with them and determine absence of the values.

Otherwise I have no easy way to provide optional values.

Consider the case where this `.env` file is necessary for a certain functionality only, so the values don't have to be set at all times. I cannot just remove them completely, as the code wouldn't compile anymore. I also cannot set them to bogus values like `foo`, because I would have to provide extra check like `if Env.elasticsearchTestUrl == "foo"` instead of a semantically more correct `if Env.elasticsearchTestUrl == null`, or add a check for `.length() == 0`.

**Comment by slhck** [comment]
I guess it's this line:

https://github.com/levibostian/dotenv/blob/4f3e5ab1143ec3518f51016f2e0f37f97c128803/generate/generate.go#L68

The value could be set to an empty string nonetheless, since apparently the user specified it.

**Comment by slhck** [comment]
I tried circumventing this with a simple env reader:

```java
import java.lang.reflect.Field;

public class EnvReader {
    private static Env env;

    public static String get(String key) throws ClassNotFoundException, IllegalAccessException {
        String packageName = EnvReader.class.getPackage().toString().replace("package ", "");
        String envClassName = packageName + ".Env"; // the generated class
        Field[] fields = Class.forName(envClassName).getFields();
        for (Field field : fields) {
            if (field.getName() == key) {
                return field.get(Env.class).toString();
            }
        }
        return null;
    }
}
```

But this creates a chicken-and-egg problem: because all my references to the Env variables now are replaced by dynamic method calls, the fields are never added to Env.java in the first place.

**Comment by levibostian** [comment]
You have a good use case here. With that being said, I agree this is a good feature request. 

The generated Env file today will only generate fields of the String data type. There is a [feature request](https://github.com/levibostian/dotenv/issues/3) to have the Env file contain more data types then String but today it's only String. Because today it's only String, I propose that this feature request will produce empty strings, only. Not `null`. I like your idea of using `null` especially for languages that use optionals like Swift/Kotlin. I propose that [this feature request](https://github.com/levibostian/dotenv/issues/3) can implement that - generating `null` values as well as other data types.
